services:
  frontend:
    build:
      context: ./app
      dockerfile: Dockerfile
    container_name: vite_charge_chart
    working_dir: /app
    volumes:
      - ./app:/app
    ports:
      - "5173:5173"
    user: "${UID}:${GID}"
